# Generated by Django 3.1.4 on 2021-02-03 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiontype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='description',
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='code',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 20, 39, 11, 679957)),
        ),
    ]
