# Generated by Django 3.1.4 on 2021-02-03 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20210203_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debit_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='debit_account', to='examination.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 20, 46, 44, 841992)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='examination.account'),
        ),
    ]
